### ISSUE TITLE
Crash when http request return illegal result with json content type 

### ISSUE THREAD

**Issue by xilin** [coderyi/NetworkEye#1]
In the line
https://github.com/coderyi/NetworkEye/blob/master/NetworkEye/NetworkEye/NEHTTPEye.m#L152

if any error happened, `returnValue` will be nil and the app will crash.

**Comment by coderyi** [comment]
I modified it, and please you try again。

https://github.com/coderyi/NetworkEye/commit/9905e327c71a76b49b397509bf44315718abf8c4

**Comment by xilin** [comment]
@coderyi It works.

There is the other question, I always get a message in the console:

`2015-11-08 12:10:39.224 MaiTian[18074:226489] WARNING: Requested sleep of 87 milliseconds, but SQLite returned 1000. Maybe SQLite wasn't built with HAVE_USLEEP=1?`

Which should be a FMDB problem `https://github.com/ccgus/fmdb/issues/411`

**Comment by coderyi** [comment]
i found when i set HAVE_USLEEP=1,it will be have other warning

**Comment by xilin** [comment]
I think I could close this issue. Thanks!
