### ISSUE TITLE
The monitor for `NSURLSession` is always on

### ISSUE THREAD

**Issue by xilin** [coderyi/NetworkEye#11]
I found out that `NEURLSessionConfiguration` is always return `NEHTTPEye` in the protocolClasses.

Can we add a configuration to close the monitor in release mode? Thanks.

**Comment by SentoCrespo** [comment]
Maybe do not include the framework itself as I think it's not a good practice to ship the app with these kind of debugging frameworks.

**Comment by xilin** [comment]
@vCrespoP Yes, you are right. But I think it would be better if we can manually specify when to enable it.

**Comment by coderyi** [comment]
thank you for your issue, I just fix it, adds a settings interface, and api has changed，

api is 

<pre>
#import "NEHTTPEye.h"
#if defined(DEBUG)||defined(_DEBUG)
    [NEHTTPEye setEnabled:NO];
#endif
</pre>
