### ISSUE TITLE
Swift + CocoaPods

### ISSUE THREAD

**Issue by SentoCrespo** [coderyi/NetworkEye#12]
Hello, I'm having some problems importing the framework from CocoaPods into a Swift project.

Podfile:
pod 'NetworkEye', '~> 0.9.8'

Bridging-Header:
# import <NetworkEye/NEHTTPEye.h>

Error when building in the bridging-header import: "Could not build module 'NetworkEye'

By going further, it seems this line is failing inside NEHTTPModelManager.h
# import "FMDB.h"

I guess it's a pod related thing but it would be super awesome if you could fix this problem as I find this tool to have great potential.

Cheers!

**Comment by coderyi** [comment]
Thanks，I do not use swift, I hope that you can find the cause, then hope you feed back to here, thank you

**Comment by raulriera** [comment]
Hey @vCrespoP , I think your bridging header should include `#import "NEHTTPEye.h`, that is how I am using it myself

**Comment by EugeneEl** [comment]
The same issue with bridge
#import "NEHTTPEye.h" - cannot find this file

**Comment by kasketis** [comment]
Hello all,
First of all I want to say well done to devs of this library.
I have created a similar library in swift which you can find here:
https://github.com/kasketis/netfox
If you want give it a try :)

**Comment by coderyi** [comment]
kasketis, I think you're great, netfox use swift solved the problem of network debugging, I hope to be able to add a link to your netfox in my readme

**Comment by kasketis** [comment]
Thanks for your kind words my friend! It will be my pleasure if you want to do so :smiley:
