### ISSUE TITLE
当一个http 请求的mimetype是text/html  但是内容是json 就打印不出来了

### ISSUE THREAD

**Issue by guoxj** [coderyi/NetworkEye#19]

**Comment by coderyi** [comment]
谢谢您反馈，请问内容既然是JSON，为什么mimetype不设置成application/json呢？

**Comment by guoxj** [comment]
@coderyi  因为有时候服务器端不是客户端可以控制的。
我提了个Pull requests, 我期望直接把返回值打印出来。而不仅仅是json的
因为有时候接口还可能是xml ，或者干脆纯文本的。
