### ISSUE TITLE
Feature request: filter of content type/request method in the monitor view

### ISSUE THREAD

**Issue by xilin** [coderyi/NetworkEye#2]
A filter in the monitor view is helpful since we always help a lot of network request.

Thanks.

**Comment by coderyi** [comment]
Which filter settings do you want, I will immediately add

**Comment by coderyi** [comment]
Thank you for your suggestion, now you can filter it through URL

**Comment by xilin** [comment]
@coderyi Thanks for the quick response! 
It would be better if we could have some simple search syntax such as:
1. url:abc.com
2. content_type:json
3. http_method:get
...

**Comment by coderyi** [comment]
thank you very much,add url ,status code, httpmethod,mimetype
