### ISSUE TITLE
How to disable  calling out the monitoring data interface in debug mode?

### ISSUE THREAD

**Issue by ghost** [coderyi/NetworkEye#28]
I always can call out  the monitoring data interface when I use a double tap or shake device in release mode. How to disable?

**Comment by coderyi** [comment]
[NEHTTPEye setEnabled:NO];

**Comment by ghost** [comment]
I imort NEHTTPEye by cocoapods and  NEHTTPEye.setEnabled(false) in swift, but don't work

**Comment by ghost** [comment]
iOS9.2(13C75), Xcode7.2(7C68)
