### ISSUE TITLE
Error in responseJSON

### ISSUE THREAD

**Issue by xtxwy** [coderyi/NetworkEye#3]
I modify data like this: (in NEHTTPEye.m)
-(id) responseJSON {
    。。。
    if(error){
        NSLog(@"JSON Parsing Error: %@", error);
        return nil;   // <= here
    }
   。。。
}

When "returnValue" is nil , the "NSJSONSerialization" will raise a NSException. So I return right now when error is not nil.

**Comment by coderyi** [comment]
i do it ,Thank you very much
