### ISSUE TITLE
在加载微信的一些web页面时经常回阻塞

### ISSUE THREAD

**Issue by qmkCamel** [coderyi/NetworkEye#31]
Requested sleep of 54 milliseconds, but SQLite returned 1000. Maybe SQLite wasn't built with HAVE_USLEEP=1?
基本上可以定位到这个地方
static int FMDBDatabaseBusyHandler(void *f, int count)

**Comment by coderyi** [comment]
目前支持 是否选择使用数据库，

pod 'NetworkEye' 将不保存拦截数据，这样将不会出现数据库写入太快的情况

如果有保存的需求则使用pod 'NetworkEye/FMDB'
