### ISSUE TITLE
不能获取到NSURLSession请求的httpbody

### ISSUE THREAD

**Issue by ChengwenY** [coderyi/NetworkEye#32]
将demo中的`UIWebView`去掉，只发送`testRequest`方法中的 "https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/AFNetworking/2.5.4/AFNetworking.podspec.json" 这个请求，发现获取不到httpbody，httpbody为空。

**Comment by LewisLauYang** [comment]
最近用post方法也是发现无法获取到httpbody
