### ISSUE TITLE
单独添加 SQLCipher 时，无法使用 加密模块。

### ISSUE THREAD

**Issue by sunbohong** [coderyi/NetworkEye#36]
Podfile

```
    pod 'FMDB/SQLCipher', '~> 2.6.2'
    pod 'NetworkEye', '~> 1.0.6'
```

当使用上面的配置时，NetworkEye 不会启动加密模块。

**Comment by coderyi** [comment]
你需要在你项目的target中Other C Flags中增加-DFMDB_SQLCipher

或者你不用pod两个 ，直接 pod 'NetworkEye/FMDB', '~> 1.0.6' 就好。

**Comment by sunbohong** [comment]
@coderyi

直接使用 pod 'NetworkEye/FMDB', '~> 1.0.6' 确实可以加载加密模块。

但是，是否可以支持单独加载？

**Comment by coderyi** [comment]
像你上面那样的话 ，你需要在你项目的target中Other C Flags中增加-DFMDB_SQLCipher

不知道你明白了吗？

我是在NEHTTPModelManager中通过FMDB_SQLCipher宏来决定是不是使用数据库

**Comment by sunbohong** [comment]
因为使用了 use_frameworks 选项，所以，在项目的target中Other C Flags中增加-DFMDB_SQLCipher 是无法起作用的
如果在 NetworkEye target中添加，则会导致每次 pod 操作后需要重新添加，成本比较高，而且容易出错

**Comment by coderyi** [comment]
那你就只有手动修改FMDB_SQLCipher 宏吧

**Comment by sunbohong** [comment]
尝试解决了一下，没有更好的方案解决这个问题。
可能需要去CocoaPods提需求才能解决这个问题。

**Comment by coderyi** [comment]
非常抱歉，不能帮到您

**Comment by sunbohong** [comment]
我已经发起了 issue 
https://github.com/CocoaPods/CocoaPods/issues/6017
如果实现了该功能，还希望你能够对应的修改一下

**Comment by coderyi** [comment]
好的 辛苦了
