### ISSUE TITLE
startLoading中NSURLConnection的问题。

### ISSUE THREAD

**Issue by zymxxxs** [coderyi/NetworkEye#38]
采用NSURLSessionDataTask发出去的请求，都会被拦截下来变成`NSURLConnection`发出去，这样iOS7之后出的这套API就没啥用处了。仅仅只是上层用了新的API来创建了一个request而已，实际是被`NSURLConnection`接管了。`NSURLSession`的共享cookies、验证策略、少一次握手等这些功能都没有了。

个人觉得是一种得不偿失的方法，请问，有没有其他的解法。

**Comment by coderyi** [comment]
好像没有什么办法，除非NEHTTPEye里面网络请求也都改成NSURLSession🙏

**Comment by zymxxxs** [comment]
@coderyi 理论上改成NSURLSession是没有问题的，其实还是有其他没有验证的问题。
* 如果所有的网络请求都被`NSURLSession`接管的话，用哪个`NSURLSessionConfiguration`就无从得知了。使用`defaultSessionConfiguration`的话还好说，如果是业务层自定义的`sessionConfiguration`那就有点尴尬了。
* RW有一篇教程是基于`NSURLConnection `，基本上该踩的坑都踩光了，改成`NSURLSession`的话，肯定要猜一边坑。
* 已知的一个问题: `NSURLProtocol`在拦截`NSURLSession`的POST请求时不能获取Request中的HTTPBody，大写的尴尬。

不过还是谢谢回复我的问题。

**Comment by zymxxxs** [comment]
@coderyi 问个题外话：如果我只是为了监控一下网络请求的耗时、流量之类的、不需要全局的重定向这些功能。那么我只需要hook 一下`NSURLConnection`和`NSURLSession `，这样子算不算是一种好的解法？

**Comment by coderyi** [comment]
可以啊  ，其实讲道理hook会好用一点，可以参考FLEX这个框架

**Comment by zymxxxs** [comment]
@coderyi thanks.

**Comment by LiuSky** [comment]
已知的一个问题: NSURLProtocol在拦截NSURLSession的POST请求时不能获取Request中的HTTPBody，大写的尴尬。 @zymxxx  请问这个问题能解决吗？
