### ISSUE TITLE
注入的疑问

### ISSUE THREAD

**Issue by dadpp** [coderyi/NetworkEye#39]
close

**Comment by coderyi** [comment]
因为你注入的是UIViewController类的viewDidLoad方法，统计自然统计不到你的VC类，你首先需要

```
    Method ori = class_getInstanceMethod([self class], @selector(viewDidLoad));

```

而不是

```
    Method ori = class_getInstanceMethod([UIViewController class], @selector(viewDidLoad));

```

**Comment by BaiCan** [comment]
+(void)injectIntoAllVcClasses{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        const SEL selectors[] = {
            @selector(viewDidLoad),
            @selector(viewWillAppear:)
//            @selector(viewDidAppear:),
//            @selector(viewWillDisappear:),
//            @selector(viewDidDisappear:),
//            @selector(viewWillLayoutSubviews),
//            @selector(viewDidLayoutSubviews)
        };
        const int numSelectors = sizeof(selectors) / sizeof(SEL);
        Class *classes = NULL;
        int numClasses = objc_getClassList(NULL, 0);
        
        if (numClasses > 0) {
            classes = (__unsafe_unretained Class *)malloc(sizeof(Class) * numClasses);
            numClasses = objc_getClassList(classes, numClasses);
            for (NSInteger classIndex = 0; classIndex < numClasses; ++classIndex) {
                Class class = classes[classIndex];
                
                if (class == [BCAPMUIViewControllerTrace class]) {
                    continue;
                }
                unsigned int methodCount = 0;
                Method *methods = class_copyMethodList(class, &methodCount);
                BOOL matchingSelectorFound = NO;
                for (unsigned int methodIndex = 0; methodIndex < methodCount; methodIndex++) {
                    for (int selectorIndex = 0; selectorIndex < numSelectors; ++selectorIndex) {
                        if (method_getName(methods[methodIndex]) == selectors[selectorIndex]) {
//                            injectIntoVcClass(class);
                            [self injectIntoVcClass:class];
                            matchingSelectorFound = YES;
                            break;
                        }
                    }
                    if (matchingSelectorFound) {
                        break;
                    }
                }
                free(methods);
            }
            free(classes);
        }
    });
}

typedef void (*_VIMP) (id,SEL,...); // 没有返回值的 IMP 指针
+(void)injectIntoVcClass:(Class)cls{
    NSBundle *mainBundle = [NSBundle bundleForClass:cls];
    if (mainBundle == [NSBundle mainBundle]) {
        original_viewDidLoad(cls);
//        original_viewWillAppear(cls);
        
        [self original_viewDidLoad:cls];
    }
}

Method viewDidLoad = class_getInstanceMethod(cls, @selector(viewDidLoad));
    _VIMP viewDidLoad_IMP = (_VIMP)method_getImplementation(viewDidLoad);
    method_setImplementation(viewDidLoad, imp_implementationWithBlock(^(id target, SEL action){
        NSTimeInterval start = [[NSDate date] timeIntervalSince1970] * 1000;
        viewDidLoad_IMP(target, @selector(viewDidLoad));
        NSTimeInterval end = [[NSDate date] timeIntervalSince1970] * 1000;
        NSLog(@"_original_viewDidLoad time :%f %@ %p", floor(end - start),cls,cls);
    }));

我如果是这样做是可以的

**Comment by coderyi** [comment]
因为这个 我没有实际注入过viewWillAppear，所以具体出什么问题我也不知道，不过看起来上面的代码没什么问题，现在那些莫名其妙的是什么问题呢

**Comment by dadpp** [comment]
比如 A 页面是一个 tableView, 分别 push A1 A2 A3 A4 A5 ,A1 ~ A5 是控制器,那么点多几次的时候, original_viewWillAppear 会在你 push A3 进入的时候调用了一次 original_viewWillAppear,这个是正确的,等你 pop 返回 A 的时候,还会再调用一次 A3 的 original_viewWillAppear,之后再调用 A 的 original_viewWillAppear,再 push A4 的时候,会先调用 A3 的original_viewWillAppear,再调用 A4的 original_viewWillAppear,返回的时候再调用一次 A3 ~ A4 的original_viewWillAppear,反复点击会反复调用之前曾经调用过的 original_viewWillAppear,感觉很迷惑,但是 viewDidLoad 是没有问题的

**Comment by coderyi** [comment]
感觉好乱 ，我也没怎么弄明白，你只能在最初hook的地方打断点 看看 哪里有问题，

**Comment by dadpp** [comment]
看不出,😅,我待会发一份到你邮箱,你有空的时候一起看看,谢谢哦

**Comment by coderyi** [comment]
最近太忙 不一定有时间，真是抱歉

**Comment by dadpp** [comment]
好了,已经解决了. 参考你的代码解决的
```
+ (void)replaceImplementationOfKnownSelector:(SEL)originalSelector onClass:(Class)class withBlock:(id)block swizzledSelector:(SEL)swizzledSelector
{
    Method originalMethod = class_getInstanceMethod(class, originalSelector);
    if (!originalMethod) {
        return;
    }
    
    IMP implementation = imp_implementationWithBlock(block);
    class_addMethod(class, swizzledSelector, implementation, method_getTypeEncoding(originalMethod));
    Method newMethod = class_getInstanceMethod(class, swizzledSelector);
    method_exchangeImplementations(originalMethod, newMethod);
}
```
更改为
```
+ (void)replaceImplementationOfSelector:(SEL)selector withSelector:(SEL)swizzledSelector forClass:(Class)cls withMethodDescription:(struct objc_method_description)methodDescription implementationBlock:(id)implementationBlock undefinedBlock:(id)undefinedBlock;
{
    if ([self instanceRespondsButDoesNotImplementSelector:selector class:cls]) {
        return;
    }
    
#ifdef __IPHONE_6_0
    IMP implementation = imp_implementationWithBlock((id)([cls instancesRespondToSelector:selector] ? implementationBlock : undefinedBlock));
#else
    IMP implementation = imp_implementationWithBlock((__bridge void *)([cls instancesRespondToSelector:selector] ? implementationBlock : undefinedBlock));
#endif
    
    Method oldMethod = class_getInstanceMethod(cls, selector);
    if (oldMethod) {
        class_addMethod(cls, swizzledSelector, implementation, methodDescription.types);
        
        Method newMethod = class_getInstanceMethod(cls, swizzledSelector);
        
        method_exchangeImplementations(oldMethod, newMethod);
    } else {
        class_addMethod(cls, selector, implementation, methodDescription.types);
    }
}

+ (BOOL)instanceRespondsButDoesNotImplementSelector:(SEL)selector class:(Class)cls;
{
    if ([cls instancesRespondToSelector:selector]) {
        unsigned int numMethods = 0;
        Method *methods = class_copyMethodList(cls, &numMethods);
        
        BOOL implementsSelector = NO;
        for (int index = 0; index < numMethods; index++) {
            SEL methodSelector = method_getName(methods[index]);
            if (selector == methodSelector) {
                implementsSelector = YES;
                break;
            }
        }
        
        free(methods);
        
        if (!implementsSelector) {
            return YES;
        }
    }
    
    return NO;
}

```
加多一个判断,是为了保证,对方没实现这个方法的时候不会奔溃
