### ISSUE TITLE
检测不到 post 请求参数 

### ISSUE THREAD

**Issue by duckls** [coderyi/NetworkEye#43]
换成get 是把参数拼接到url 后面

**Comment by ioser9527** [comment]
post请求方式变了，可以自己实现这部分
在NEHTTPModel类的setNe_request:方法中实现
if ([ne_request HTTPBody].length>512) {
        self.requestHTTPBody=@"requestHTTPBody too long";
    }else if (![ne_request HTTPBody]){
        
           if ([ne_request.HTTPMethod isEqualToString:@"POST"]) {
                  if (!ne_request.HTTPBody) {
                     uint8_t rd[1024] = {0};
                      NSInputStream *stream = ne_request.HTTPBodyStream;
                       NSMutableData *data = [[NSMutableData alloc] init];
                     [stream open];
                      while ([stream hasBytesAvailable]) {
                          NSInteger len = [stream read:rd maxLength:1024];
                        if (len > 0 && stream.streamError == nil) {
                            [data appendBytes:(void *)rd length:len];
                          }
                      }
                      self.requestHTTPBody=[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
                      [stream close];
                }
            }
    }

**Comment by coderyi** [comment]
已经修改，请更新版本到1.1.2
