### ISSUE TITLE
Crash bug 

### ISSUE THREAD

**Issue by jackrex** [coderyi/NetworkEye#5]
JSON Parsing Error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

![image](https://cloud.githubusercontent.com/assets/3631994/11025723/264ab7bc-86da-11e5-9a5b-581ca5e45b43.png)

returnValue 为nil 会导致crash

异常情况求处理

**Comment by jackrex** [comment]
好像看你解决了....
Pod 有更新没

**Comment by coderyi** [comment]
刚刚更新了 0.9.6
